version: "3"
services:
  jupyter:
    container_name: jupyter-titanic
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./data:/project/data
      - ./notebooks:/project/notebooks
    # environment:
    #   JUPYTER_TOKEN: 6P7R9SATCVDWEYGZH2K4M5N6Q8R9SBUCVDXFYGZJ3K4M6P7Q8SATBUDWEX